### Criar os dados ###
POST  http://localhost:8080/api/v1/temperature-humidity/create HTTP/1.1
content-type: application/json

{
    "temperature": "10",
    "humidity": "10",
    "smoke": "0"
}

### Obter os dados ###
GET  http://localhost:8080/api/v1/temperature-humidity/ HTTP/1.1
